### ISSUE TITLE
ring buffer update

### ISSUE THREAD

**Issue by shubham-shahh** [ZJU-FAST-Lab/EGO-Planner-v2#1]
Hi @bigsuperZZZX, Thank you so much for this update
I have a few questions, I went through the code base and found `map_size_x, map_size_y, map_size_z` are there in launch files but it is not used in grid_map.cpp but it is used in gridmap_bigmap.cpp. can you please explain me, which one is used when?

the second question is, I see 4 workspaces, along with a visual representation. can you please share a brief of how they differ from each other fundamentally?

Thanks again and kudos for amazing work

**Comment by bigsuperZZZX** [comment]
1. You could choose the one you want.
2. They differ in planning algorithms. For detailed information, please read our published paper in readme.md.

**Comment by shubham-shahh** [comment]
> 1. You could choose the one you want.
> 2. They differ in planning algorithms. For detailed information, please read our published paper in readme.md.

okay, Thank you so much, I'll go through it. 
I'll close this issue for now
