### ISSUE TITLE
2D planning?

### ISSUE THREAD

**Issue by bxc237** [ZJU-FAST-Lab/EGO-Planner-v2#15]
Hi, thank you for sharing this great work. I am wondering if there is a way to limit the planner to just planning the trajectory in the 2D plane? Thanks.

**Comment by bigsuperZZZX** [comment]
You could just inflate a great amount of the obstacles in z direction.

**Comment by shubham-shahh** [comment]
> You could just inflate a great amount of the obstacles in z direction.

How can we do that?

**Comment by bigsuperZZZX** [comment]
Please refer to this https://github.com/ZJU-FAST-Lab/ego-planner/issues/52#issuecomment-1407586929
