### ISSUE TITLE
 The optimized trajectories will collide with obstacles

### ISSUE THREAD

**Issue by qycqycqyc** [ZJU-FAST-Lab/EGO-Planner-v2#21]
when I run single_drone_interactive.launch with rotors_simulators,I find that the red optimized trajectoris collide with obstacles.
![2023-04-18 09-58-05屏幕截图](https://user-images.githubusercontent.com/48520573/232651051-1f9ac216-fa00-4306-a26d-530261010b69.png)
![2023-04-18 09-58-17屏幕截图](https://user-images.githubusercontent.com/48520573/232651652-3bb11593-7d5e-41c9-b8bf-eefce73f0832.png)

![2023-04-18 09-58-35屏幕截图](https://user-images.githubusercontent.com/48520573/232651038-755c411e-7887-4ab5-841f-044647c31f29.png)

**Comment by qycqycqyc** [comment]
@at first the trajectory is ok,but then,the red will be close to the obstacles,at last,the uav will collide the the obstacles.

**Comment by qycqycqyc** [comment]
@bigsuperZZZX

**Comment by qycqycqyc** [comment]
@ZhepeiWang please do me a favor

**Comment by qycqycqyc** [comment]
这是所有设置的参数
<launch>
    <arg name="map_size_x" value="200.0"/>
    <arg name="map_size_y" value="200.0"/>
    <arg name="map_size_z" value=" 30.0"/>

    <arg name="drone_id" value="0"/>
    <arg name="planning_horizon" value="7.5" />
    <arg name="use_multitopology_trajs" value="false" />

    <arg name="max_vel" value="1" />
    <arg name="max_acc" value="0.5" />
    <arg name="max_jer" value="10.0" />

    <arg name="odom_topic" value="/m100/ground_truth/odometry"/>
    <arg name="cloud_topic" value="/velodyne_points"/>

    <arg name="camera_pose_topic" value="pcl_render_node/camera_pose"/>
    <arg name="depth_topic" value="pcl_render_node/depth"/>
    <arg name="cx" value="321.04638671875"/>
    <arg name="cy" value="243.44969177246094"/>
    <arg name="fx" value="387.229248046875"/>
    <arg name="fy" value="387.229248046875"/>

    <node pkg="ego_planner" name="drone_$(arg drone_id)_ego_planner_node" type="ego_planner_node" output="screen">
        <remap from="~odom_world" to="$(arg odom_topic)"/>

        <remap from="~planning/trajectory" to = "/drone_$(arg drone_id)_planning/trajectory"/>
        <remap from="~planning/heartbeat" to = "/drone_$(arg drone_id)_traj_server/heartbeat"/>

        <remap from="/goal" to = "/goal_with_id"/>
        <remap from="~grid_map/odom" to="$(arg odom_topic)"/>
        <remap from="~grid_map/cloud" to="$(arg cloud_topic)"/>
        <remap from="~grid_map/pose"   to = "$(arg camera_pose_topic)"/>
        <remap from="~grid_map/depth" to = "$(arg depth_topic)"/>
        
        <param name="fsm/thresh_replan_time" value="1.0" type="double"/>
        <param name="fsm/planning_horizon" value="$(arg planning_horizon)" type="double"/>
        <param name="fsm/emergency_time" value="1.0" type="double"/>
        <param name="fsm/fail_safe" value="true"/>

        <param name="grid_map/resolution" value="0.1" />
        <param name="grid_map/map_size_x" value="$(arg map_size_x)" />
        <param name="grid_map/map_size_y" value="$(arg map_size_y)" />
        <param name="grid_map/map_size_z" value="$(arg map_size_z)" />
        <param name="grid_map/local_update_range_x" value="10" />
        <param name="grid_map/local_update_range_y" value="10" />
        <param name="grid_map/local_update_range_z" value="10" />

        <param name="grid_map/obstacles_inflation" value="0.1" />
        <param name="grid_map/local_map_margin" value="10"/>
        <param name="grid_map/enable_virtual_wall" value="false"/>
        <param name="grid_map/virtual_ceil" value="3.0"/>
        <param name="grid_map/virtual_ground" value="-0.1"/>
        <param name="grid_map/ground_height" value="-0.01"/>
        
        <param name="grid_map/cx" value="$(arg cx)"/>
        <param name="grid_map/cy" value="$(arg cy)"/>
        <param name="grid_map/fx" value="$(arg fx)"/>
        <param name="grid_map/fy" value="$(arg fy)"/>
        
        <param name="grid_map/use_depth_filter" value="true"/>
        <param name="grid_map/depth_filter_tolerance" value="0.15"/>
        <param name="grid_map/depth_filter_maxdist" value="5.0"/>
        <param name="grid_map/depth_filter_mindist" value="0.2"/>
        <param name="grid_map/depth_filter_margin" value="2"/>
        <param name="grid_map/k_depth_scaling_factor" value="1000.0"/>
        <param name="grid_map/skip_pixel" value="2"/>
        
        <param name="grid_map/p_hit" value="0.65"/>
        <param name="grid_map/p_miss" value="0.35"/>
        <param name="grid_map/p_min" value="0.12"/>
        <param name="grid_map/p_max" value="0.90"/>
        <param name="grid_map/p_occ" value="0.80"/>
        <param name="grid_map/fading_time" value="1000.0"/>
        <param name="grid_map/min_ray_length" value="0.1"/>
        <param name="grid_map/max_ray_length" value="4.5"/>
        <param name="grid_map/visualization_truncate_height" value="20"/>
        <param name="grid_map/show_occ_time" value="false"/>
        <param name="grid_map/pose_type" value="1"/>
        <param name="grid_map/frame_id" value="world"/>
        
        <param name="manager/max_vel" value="$(arg max_vel)" type="double"/>
        <param name="manager/max_acc" value="$(arg max_acc)" type="double"/>
        <param name="manager/polyTraj_piece_length" value="1.5" type="double"/>
        <param name="manager/feasibility_tolerance" value="0.05" type="double"/>
        <param name="manager/planning_horizon" value="$(arg planning_horizon)" type="double"/>
        <param name="manager/use_multitopology_trajs" value="$(arg use_multitopology_trajs)" type="bool"/>
        <param name="manager/drone_id" value="$(arg drone_id)"/>
        
        <param name="optimization/constraint_points_perPiece" value="5" type="int"/>
        <param name="optimization/weight_obstacle" value="10000.0" type="double"/>
        <param name="optimization/weight_obstacle_soft" value="5000.0" type="double"/>
        <param name="optimization/weight_swarm" value="10000.0" type="double"/>
        <param name="optimization/weight_feasibility" value="10000.0" type="double"/>
        <param name="optimization/weight_sqrvariance" value="10000.0" type="double"/>
        <param name="optimization/weight_time" value="10.0" type="double"/>
        <param name="optimization/obstacle_clearance" value="1.5" type="double"/>
        <param name="optimization/obstacle_clearance_soft" value="0.4" type="double"/>
        <param name="optimization/swarm_clearance" value="0.15000000000000002" type="double"/>

        <param name="optimization/max_vel" value="$(arg max_vel)" type="double"/>
        <param name="optimization/max_acc" value="$(arg max_acc)" type="double"/>
        <param name="optimization/max_jer" value="$(arg max_jer)" type="double"/>
    </node>

    
    <node pkg="ego_planner" name="drone_$(arg drone_id)_traj_server" type="traj_server" output="screen">
        <remap from="position_cmd" to="drone_$(arg drone_id)_planning/pos_cmd"/>
        <remap from="~planning/trajectory" to="drone_$(arg drone_id)_planning/trajectory"/>
        <param name="traj_server/time_forward" value="1.0" type="double"/>
    </node>

    
    <include file="$(find mbplanner)/launch/mbplanner_m100_sim_cave2.launch">
    </include>

    <node name="rviz" pkg="rviz" type="rviz" args="-d $(find ego_planner)/launch/mbp.rviz" required="true">
    </node>

</launch>

**Comment by qycqycqyc** [comment]
I think it is necessary to copy the optimized trajectory, that is, the safe distance of the up, down, left, and right of the red trajectory, to generate a trajectory, and then detect the safety of each trajectory to prevent the trajectory from being close to obstacles, and The above mentioned bugs

**Comment by bigsuperZZZX** [comment]
A collision means you have to enlarge the inflation.

**Comment by qycqycqyc** [comment]
But,in the grid_map.cpp，it said the limit of inflation is 4 resolutions



---Original---
From: "Xin ***@***.***&gt;
Date: Sun, May 14, 2023 21:01 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [ZJU-FAST-Lab/EGO-Planner-v2]  The optimized trajectories will collide with obstacles (Issue #21)




 
A collision means you have to enlarge the inflation.

**Comment by bigsuperZZZX** [comment]
It's just an [instruction](https://github.com/ZJU-FAST-Lab/EGO-Planner-v2/blob/9d85475ea7b9bf5c112cf7c3c3d0d3f9e96d9010/swarm-playground/main_ws/src/planner/plan_env/src/grid_map.cpp#L49). You can following it to enlarge the resolution as well.

**Comment by qycqycqyc** [comment]
I tried to add an envelope to the UAV, that is, four parallel tracks up and down, left and right, enclosing the UAV and detecting it at the same time



---Original---
From: "Xin ***@***.***&gt;
Date: Sun, May 14, 2023 21:24 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [ZJU-FAST-Lab/EGO-Planner-v2]  The optimized trajectories will collide with obstacles (Issue #21)




 
It's just a instruction. You can following it to enlarge the resolution as well.
