### ISSUE TITLE
How is trajectory tracking done?

### ISSUE THREAD

**Issue by JJq-Zhou** [ZJU-FAST-Lab/EGO-Planner-v2#4]
I see you have mentioned PX-4Autopilot, what trajectory tracking package/algorithm is used with PX4? @bigsuperZZZX @ZhepeiWang

**Comment by JJq-Zhou** [comment]
@bigsuperZZZX @ZhepeiWang, please  respond

**Comment by bigsuperZZZX** [comment]
Our controller is modified from [this package](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/tree/experiment/onboard_computer/controller/n3ctrl).

**Comment by JJq-Zhou** [comment]
I can not convert it mavros message. please help me with that. please tell me the mavros message name and how can i convert, controller's output to mavros message @bigsuperZZZX

**Comment by bigsuperZZZX** [comment]
You would like to follow [our course](https://www.bilibili.com/video/BV1WZ4y167me?p=1) of drone building and download code from [this link](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/tree/master/src/realflight_modules/px4ctrl).
