### ISSUE TITLE
yaw and yaw rate are same

### ISSUE THREAD

**Issue by shubham-shahh** [ZJU-FAST-Lab/EGO-Planner-v2#8]
Hi @bigsuperZZZX , why does the planner publish the equal Yaw and Yaw rate?
yaw: 0.563052045148
yaw_dot: 0.563052045148

in traj_server.cpp, In function calculate_yaw()
`yaw_yawdot.second = yaw_temp;`

makes them equal.
why is this required?

thanks

**Comment by shubham-shahh** [comment]
Hi @bigsuperZZZX, any update on this?

**Comment by bigsuperZZZX** [comment]
I think it is a mistake. Since the controller only takes the yaw commands as the input, yaw_dot is ignored.

**Comment by shubham-shahh** [comment]
> I think it is a mistake. Since the controller only takes the yaw commands as the input, yaw_dot is ignored.

commenting that line mentioned above should help right? If I want to use yaw and yawrate?

**Comment by bigsuperZZZX** [comment]
yawrate is ignored now, so just comment it.

**Comment by shubham-shahh** [comment]
> yawrate is ignored now, so just comment it.

Ignored where? I am willing to use yaw rate

**Comment by bigsuperZZZX** [comment]
Ignored in the controller from drone simulation
