### ISSUE TITLE
occupancy grid not updating

### ISSUE THREAD

**Issue by shubham-shahh** [ZJU-FAST-Lab/EGO-Planner-v2#9]
Hi @bigsuperZZZX,
I have one question. I tested ego-planner-v2 with point cloud data in the real world. after running the planner for some time, the occupancy grid is not updated, it says the drone is in a obstacle and can be visualised in Rviz, but in real world, there are no obstacles, and if I restart the planner, it works, and the grid is updated. below I've attached a picture. can you please tell me, the probable cause for this problem?
![Screenshot from 2022-07-18 16-37-29](https://user-images.githubusercontent.com/51359628/179499410-38509812-5b2a-412c-8c0d-14052e0dd640.png)
![Screenshot from 2022-07-18 18-10-15](https://user-images.githubusercontent.com/51359628/179513200-386dfdb8-5da5-4e60-b613-d0793d7baead.png)

**Comment by bigsuperZZZX** [comment]
Maybe your drone stays too close to an obstacle. Therefore the resolution error may cause this problem.

**Comment by shubham-shahh** [comment]
> Maybe your drone stays too close to an obstacle. Therefore the resolution error may cause this problem.

Hi @bigsuperZZZX, thanks for the response
But I can confirm that the drone was not close to the obstacle, as you can see in the raw point cloud on the left.
what is resolution error?

thanks
